# Generated by Django 4.2.3 on 2023-10-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanage', '0008_alter_classroom_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='image',
            field=models.ImageField(default='images/classimg1.jpg', null=True, upload_to='images/'),
        ),
    ]
