# Generated by Django 4.0.5 on 2023-07-07 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.slider')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
