# Generated by Django 4.0.5 on 2023-07-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_rename_image_slider_slider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Bkash', 'Bkash'), ('Nagad', 'Nagad')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='payment_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='trx_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
